SAMPLES = [
    {
        "name": "Black queen vs white king",
        "input": [
            "w",
            "     k  ",
            " p      ",
            "       p",
            "        ",
            "   b   P",
            "P  P  p ",
            " q    P ",
            "K       ",
        ],
        "output": "mate",
    },
    {
        "name": "Rooks throw bricks for black king!",
        "input": [
            "b",
            "k       ",
            "      p ",
            "        ",
            "    p   ",
            "    P   ",
            " R    P ",
            "R       ",
            "    K   ",
        ],
        "output": "mate",
    },
    {
        "name": "Starting position",
        "input": [
            "b",
            "rnbqkbnr",
            "pppppppp",
            "        ",
            "        ",
            "        ",
            "        ",
            "PPPPPPPP",
            "RNBQKBNR",
        ],
        "output": "not mate",
    },
    {
        "name": "Just a game",
        "input": [
            "w",
            "r   k  r",
            "ppp  pbp",
            "  qp  p ",
            "n   pbB ",
            "  PPP n ",
            "     N P",
            "PP   PP ",
            "RN QKB R",
        ],
        "output": "not mate",
    },
    {
        "name": "Scholar's Mate",
        "input": [
            "b",
            "r bqkbnr",
            "pppp Q p",
            "  n   p ",
            "    p   ",
            "  B P   ",
            "        ",
            "PPPP PPP",
            "RNB K NR",
        ],
        "output": "mate",
    },
    {
        "name": "Italian Game Smothered Mate",
        "input": [
            "w",
            "r b kbnr",
            "pppp Npp",
            "        ",
            "        ",
            "    q   ",
            "     n  ",
            "PPPPBP P",
            "RNBQKR  ",
        ],
        "output": "mate",
    },
    {
        "name": "Modern defense",
        "input": [
            "b",
            "rnbqkbnr",
            "ppp  ppp",
            "        ",
            "   p    ",
            "    Pp  ",
            "     N  ",
            "PPPP  PP",
            "RNBQKB R",
        ],
        "output": "not mate",
    },
    {
        "name": "Five to one",
        "input": [
            "w",
            "   k    ",
            "  q b   ",
            "      b ",
            "       r",
            "   K    ",
            "        ",
            "  n     ",
            "        ",
        ],
        "output": "mate",
    },
    {
        "name": "special - 1",
        "input": [
            "w",
            "        ",
            "        ",
            "    k   ",
            "        ",
            "    K   ",
            "r       ",
            "    n   ",
            "        ",
        ],
        "output": "not mate",
    },
    {
        "name": "special - 2",
        "input": [
            "w",
            "        ",
            "        ",
            "    k   ",
            "   p    ",
            "    K   ",
            "r       ",
            "    n   ",
            "        ",
        ],
        "output": "mate",
    },
    {
        "name": "special - 3",
        "input": [
            "b",
            "        ",
            "        ",
            "    K   ",
            "   P    ",
            "    k   ",
            "R       ",
            "    N   ",
            "        ",
        ],
        "output": "not mate",
    },
    {
        "name": "special - 4",
        "input": [
            "b",
            "        ",
            "        ",
            "  B K   ",
            "        ",
            "    k   ",
            "R       ",
            "    N   ",
            "        ",
        ],
        "output": "mate",
    },
    {
        "name": "special - 5",
        "input": [
            "w",
            " q  k   ",
            "b       ",
            "b    n  ",
            "       r",
            "    K   ",
            "        ",
            "   n    ",
            "        ",
        ],
        "output": "mate",
    },
    {
        "name": "special - 6",
        "input": [
            "w",
            " Q  k   ",
            "B       ",
            "B    N  ",
            "       R",
            "    K   ",
            "        ",
            "   N    ",
            "        ",
        ],
        "output": "not mate",
    },
    {
        "name": "special - 7",
        "input": [
            "b",
            " Q  k   ",
            "B       ",
            "B    N  ",
            "       R",
            "    K   ",
            "        ",
            "   N    ",
            "        ",
        ],
        "output": "not mate",
    },
    {
        "name": "extra-1",
        "input": [
            "w",
            "    k   ",
            "        ",
            "        ",
            "        ",
            "        ",
            "     n  ",
            "   PPP  ",
            "   QKB  ",
        ],
        "output": "mate",
    },
    {
        "name": "extra-2",
        "input": [
            "b",
            "k       ",
            " P      ",
            "  N     ",
            "        ",
            "        ",
            "        ",
            "        ",
            "    K   ",
        ],
        "output": "mate",
    },
    {
        "name": "extra-3",
        "input": [
            "b",
            "K    k  ",
            " p      ",
            "  n     ",
            "        ",
            "        ",
            "        ",
            "        ",
            "        ",
        ],
        "output": "not mate",
    },
    {
        "name": "extra-4",
        "input": [
            "w",
            "k     bb",
            "     bb ",
            "    bb  ",
            "   bb   ",
            "  bb    ",
            " bb   K ",
            "bb      ",
            "b       ",
        ],
        "output": "mate",
    },
]
